name: Cache Dependencies

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Cache APT packages
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt/archives
          ~/.cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/setup.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-
          
    - name: Cache NASM
      uses: actions/cache@v3
      with:
        path: |
          /usr/bin/nasm
          /usr/share/nasm
        key: ${{ runner.os }}-nasm-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-nasm-
          
    - name: Cache QEMU
      uses: actions/cache@v3
      with:
        path: |
          /usr/bin/qemu-system-i386
          /usr/share/qemu
        key: ${{ runner.os }}-qemu-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-qemu-
          
    - name: Cache GRUB
      uses: actions/cache@v3
      with:
        path: |
          /usr/bin/grub-mkrescue
          /usr/lib/grub
        key: ${{ runner.os }}-grub-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-grub-
          
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          nasm \
          qemu-system-x86 \
          grub-pc-bin \
          grub-common \
          xorriso \
          mtools
          
    - name: Cache compiled objects
      uses: actions/cache@v3
      with:
        path: |
          kernel/*.o
          *.bin
          *.iso
          *.img
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-
          
    - name: Build GooseOS
      run: |
        make clean
        make
        make gooseos.iso
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gooseos-build
        path: |
          kernel.bin
          gooseos.iso
          disk.img
